[package]
name = "pokedriver_derive"
version = "0.1.0"
authors = ["supercmmetry <vishaals2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.23"
quote = "1.0.6"

[lib]
proc-macro = true
